### ISSUE TITLE
fish with same tag_id but different gen_id

### ISSUE THREAD

**Issue by katcatalano** [pinskylab/genomics#13]
L2616, gen_id=1481, tag_id=985153000375244
L4938, gen_id=4605,  tag_id=985153000375244
Maybe they just didn't match genetically?

**Comment by mstuart1** [comment]
Double checked and this tag was scanned at the times that these fish were captured, so there is no tag_id type-o.  Next step will be to check id analysis and see if these fish were compared genetically.

**Comment by mstuart1** [comment]
These fish were in the genepop but did not match to each other as identity matches in curves even though they have the same tag_id.  @katcatalano will look into this and report back a genotyping error number which will clarify if the genotypes were close to the match threshold or if there may be a lab error somewhere.

**Comment by katcatalano** [comment]
The following fish have a different gen_id, but the same tag_id, so they didn't match with Cervus but matched with their tag_id. Based on my code, there was only a 6.3% mismatch in the genotypes of these fish, which means Cervus should have identified these fish as an identity match.

APCL15_373270/ L3005/ gen_id= 1298
and
APCL16_292/ L5054/ gen_id= 1670

I think that we may need to adjust our Cervus parameters and re-do the identity analysis, and I'll continue this comment on the appropriate issue #22

**Comment by katcatalano** [comment]
As commented in #22 I started an identity analysis in Colony to find regenotyped individuals that Cervus may have missed (because it can't handle missing genotypes). I will hand the output over to Michelle for identity post-processing to be sure these results make sense and check them against Cervus results.

Adding @agdedrick  as an assignee in this issue to keep her in the loop, and I will post updates here rather than #22
