### ISSUE TITLE
Genepop won't write to be readable by Cervus

### ISSUE THREAD

**Issue by mstuart1** [pinskylab/genomics#16]

**Comment by mstuart1** [comment]
It appears that the names of samples are missing.  Working with [remove_regenos.Rmd](https://github.com/pinskylab/genomics/blob/master/scripts/remove_regenos.Rmd) to generate a genepop that serves can read.

**Comment by katcatalano** [comment]
Okay, sounds good.

**Comment by mstuart1** [comment]
Had changed name of names column to ligation_id to avoid conflicts with the names() function and this had caused writing issues at the genepop writing portion of the code.  Now fixed and cervus is running id analysis
