### ISSUE TITLE
link for lab protocols within genomics repo is broken

### ISSUE THREAD

**Issue by jahoey** [pinskylab/genomics#38]

**Comment by mstuart1** [comment]
When I click on the link in the README it works.

**Comment by jahoey** [comment]
It doesn't work for me? The 'laboratory' link:
<img width="920" alt="Screen Shot 2020-07-23 at 9 05 34 AM" src="https://user-images.githubusercontent.com/9931658/88289833-d6a44400-ccc3-11ea-877c-df1e497ea9e8.png">

**Comment by mstuart1** [comment]
Fixed it.
________________________________
