### ISSUE TITLE
genepop file with column names as dDocent contig ID

### ISSUE THREAD

**Issue by katcatalano** [pinskylab/genomics#5]
To filter out the linked loci, I need the 2019-01-03_norecap.gen file to have the loci labeled with their dDocent contig id, rather than the numbers they are now. Any chance I can get a new genepop with those column names please? Thanks so much!

**Comment by mstuart1** [comment]
I renamed the norecap.gen to represent the contents and not the date, so now seq-03-33_norecap.gen contains column headers in the style "dDocent_contig_1045" and none of the Ligation ids have a ".F" after them, though some are "L2345.L3334" to represent that an individual was regenotyped and the sequencing data was concatenated.
